CREATE USER user_rhs WITH PASSWORD 'password';
CREATE USER user_us WITH PASSWORD 'password';
-- CREATE USER user_ps WITH PASSWORD 'password';

CREATE DATABASE db;
CREATE DATABASE product_db;
-- CREATE DATABASE ...;

GRANT ALL PRIVILEGES ON DATABASE db TO user_rhs;
GRANT ALL PRIVILEGES ON DATABASE product_db TO user_us;
-- GRANT ALL PRIVILEGES ON DATABASE ... TO user_ps;
